Create pedal feature
matheusberger/pb-ios pull request #1
Opened 2023-08-23 00:55 UTC by matheusmigge

2023-08-23 01:03 UTC, matheusberger commented on PedalCore/HomeView.swift
>      }
Nice

2023-08-23 01:03 UTC, matheusmigge commented on PedalCore/HomeView.swift
>      }
Very nice.

2023-08-25 18:35 UTC, matheusberger commented on PedalCore/ViewModels/HomeViewModel.swift
> +        print(pedals)
Remember to remove any print() code you used before the final PR review
```suggestion
```

2023-08-25 18:36 UTC, matheusberger requested changes
Please remove the print in HomeViewModel the re-request my review.

2023-08-30 01:56 UTC, matheusberger approved these changes

2023-08-30 01:57 UTC, merged